# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/AzurePipelineProjectSample.sln'
  project: '**/AzurePipelineProjectSample.csproj'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  name: NugetToolInstaller

- task: NuGetCommand@2
  name: 'RestoreNuget'
  inputs:
    command: 'restore'
    restoreSolution: '$(solution)'

- task: DotNetCoreCLI@2
  name: 'BuildArtifacts'
  inputs:
    command: 'publish'
    publishWebProjects: false
    projects: '$(project)'
    arguments: --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    zipAfterPublish: true

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'AzureDemo'
    publishLocation: 'Container'
